name: Build 'yocto-base' Docker image

on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: ['main']

env:
  GHCR: ghcr.io/${{ github.repository }}
  REPOSITORY_LC:

jobs:
  buildBaseImage:
    name: Build base Docker image
    runs-on: ubuntu-latest
    steps:
      - name: set lower case on full repo name
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get repo metadata
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.GHCR }}

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (but DO NOT PUSH) image to GHCR
        # updates to PR branch only
        if: github.event.pull_request.merged == false
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ steps.metadata.outputs.tags }}-${{ github.sha }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Build & push (new 'latest') image to GHCR
        # when we merge to 'main'
        if: github.event.pull_request.merged
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ steps.metadata.outputs.tags }}-${{ github.sha }}
            ghcr.io/${{ env.REPOSITORY_LC }}:latest
          labels: ${{ steps.metadata.outputs.labels }}
